# Numpy

In [6]:
import numpy as np

In [10]:
np.arange(10)  #the output will be in array as well


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
mylist = [0,1,2,3,4,5]
mylist
type(mylist)

list

In [14]:
arr = np.array(mylist)  #converting list to array
arr

array([0, 1, 2, 3, 4, 5])

In [16]:
print(type(mylist))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(10,40,5)  #this is 1D ARRAY O/P

array([10, 15, 20, 25, 30, 35])

### zeros

In [21]:
np.zeros(5)  #SYS CONSIDER BY DEFAULT FLOAT

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [24]:
np.zeros((2,2))   #printing 2D ARRAY

array([[0., 0.],
       [0., 0.]])

In [35]:
np.zeros((10 ,5), dtype=int)  #2d printing,where first paramter is row and then coloumn

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [30]:
np.ones(4)


array([1., 1., 1., 1.])

In [32]:
np.ones(3)

array([1., 1., 1.])

In [33]:
np.ones((4,5))  #2d matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.ones((4,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## random

In [37]:
random(3)  #random is not defined

NameError: name 'random' is not defined

In [38]:
np.random.rand(4)  #but here it is defined
                   #rand is a function       

array([0.33314349, 0.5167854 , 0.01838945, 0.61675787])

In [40]:
np.random.rand(4) #all are floatting numbers

array([0.89917788, 0.31665305, 0.56372193, 0.95835001, 0.731479  ])

In [41]:
np.random.rand(3,4)  #it is defined for rows and columns

array([[0.99444354, 0.82732151, 0.10966271, 0.78918084],
       [0.54000032, 0.96554969, 0.91714747, 0.9474161 ],
       [0.78135633, 0.3395516 , 0.97141786, 0.60800516]])

In [45]:
np.random.randint(5) #it will genrate random no. b/w 0 to 4

2

In [49]:
np.random.randint(10)  #b/w 0 t 9

6

In [50]:
np.random.randint(5,10,3)  # three random numbers,B/W 5 TO 10
                           #THIS IS NOT STEP INDEXING

array([7, 7, 5], dtype=int32)

In [52]:
np.random.randint(5,10,[5,7]) #5 ROWS AND 7 COLUMNS, AND RANGE IS 5 TO 10 (N-1)

array([[8, 7, 7, 6, 7, 9, 9],
       [7, 9, 7, 8, 5, 5, 8],
       [7, 8, 8, 7, 6, 6, 9],
       [8, 5, 8, 6, 8, 5, 6],
       [6, 7, 6, 6, 9, 8, 8]], dtype=int32)

In [53]:
np.random.randint(10,2)  #the first ARG should be lesser than 2nd ARG

ValueError: low >= high

In [54]:
np.random.randint(-10,2)

-6

In [56]:
np.random.randint(-10,2,5) #ONLY 5 RANDOM NUMBER

array([-6, -5, -4,  0, -1], dtype=int32)

In [59]:
np.random.randint(10,40,(10,10))

array([[12, 28, 39, 11, 15, 13, 27, 31, 11, 11],
       [39, 34, 13, 37, 29, 28, 20, 30, 34, 37],
       [35, 19, 24, 25, 37, 18, 37, 17, 13, 36],
       [34, 31, 14, 30, 15, 27, 30, 15, 35, 31],
       [39, 28, 14, 36, 23, 25, 10, 12, 12, 17],
       [23, 37, 38, 10, 28, 36, 27, 33, 39, 14],
       [25, 11, 37, 35, 23, 14, 15, 30, 27, 29],
       [23, 15, 21, 29, 32, 11, 38, 33, 30, 15],
       [31, 22, 33, 19, 30, 29, 37, 37, 23, 29],
       [31, 20, 25, 29, 27, 33, 36, 38, 12, 18]], dtype=int32)

### how to remove this dtype int32

In [61]:
arr1 = np.random.randint(10,40,(10,10))

In [62]:
print(arr1) #dtype= int 32 is removed now

[[16 31 33 14 26 27 15 34 19 12]
 [23 30 14 28 29 19 36 17 12 14]
 [33 30 17 24 32 12 37 30 14 19]
 [36 23 37 34 33 14 23 16 33 24]
 [39 11 30 20 19 27 14 30 29 27]
 [17 23 36 36 10 23 31 15 37 25]
 [10 11 27 30 10 34 31 31 21 21]
 [12 38 36 28 15 25 17 13 13 21]
 [37 25 27 30 29 29 19 12 22 27]
 [33 25 21 11 31 26 22 25 29 18]]


## indexing and slicing in array

In [65]:
arr1[:]

array([[16, 31, 33, 14, 26, 27, 15, 34, 19, 12],
       [23, 30, 14, 28, 29, 19, 36, 17, 12, 14],
       [33, 30, 17, 24, 32, 12, 37, 30, 14, 19],
       [36, 23, 37, 34, 33, 14, 23, 16, 33, 24],
       [39, 11, 30, 20, 19, 27, 14, 30, 29, 27],
       [17, 23, 36, 36, 10, 23, 31, 15, 37, 25],
       [10, 11, 27, 30, 10, 34, 31, 31, 21, 21],
       [12, 38, 36, 28, 15, 25, 17, 13, 13, 21],
       [37, 25, 27, 30, 29, 29, 19, 12, 22, 27],
       [33, 25, 21, 11, 31, 26, 22, 25, 29, 18]], dtype=int32)

In [66]:
len(arr1)

10

In [67]:
arr1.shape #DIMENSION OF AN ARRAY(ROW AND COLUMN COUNT)

(10, 10)

In [68]:
arr1

array([[16, 31, 33, 14, 26, 27, 15, 34, 19, 12],
       [23, 30, 14, 28, 29, 19, 36, 17, 12, 14],
       [33, 30, 17, 24, 32, 12, 37, 30, 14, 19],
       [36, 23, 37, 34, 33, 14, 23, 16, 33, 24],
       [39, 11, 30, 20, 19, 27, 14, 30, 29, 27],
       [17, 23, 36, 36, 10, 23, 31, 15, 37, 25],
       [10, 11, 27, 30, 10, 34, 31, 31, 21, 21],
       [12, 38, 36, 28, 15, 25, 17, 13, 13, 21],
       [37, 25, 27, 30, 29, 29, 19, 12, 22, 27],
       [33, 25, 21, 11, 31, 26, 22, 25, 29, 18]], dtype=int32)

In [69]:
arr1[3] #will print the 3rd row,ROW WILL START FROM 0

array([36, 23, 37, 34, 33, 14, 23, 16, 33, 24], dtype=int32)

In [71]:
arr1[:4]  

array([[16, 31, 33, 14, 26, 27, 15, 34, 19, 12],
       [23, 30, 14, 28, 29, 19, 36, 17, 12, 14],
       [33, 30, 17, 24, 32, 12, 37, 30, 14, 19],
       [36, 23, 37, 34, 33, 14, 23, 16, 33, 24]], dtype=int32)

### in slicing n-1 will always be there

In [73]:
arr1[2:7]

array([[33, 30, 17, 24, 32, 12, 37, 30, 14, 19],
       [36, 23, 37, 34, 33, 14, 23, 16, 33, 24],
       [39, 11, 30, 20, 19, 27, 14, 30, 29, 27],
       [17, 23, 36, 36, 10, 23, 31, 15, 37, 25],
       [10, 11, 27, 30, 10, 34, 31, 31, 21, 21]], dtype=int32)

In [75]:
arr1[2,7]  #2nd row and 7th column

np.int32(30)

In [76]:
arr1

array([[16, 31, 33, 14, 26, 27, 15, 34, 19, 12],
       [23, 30, 14, 28, 29, 19, 36, 17, 12, 14],
       [33, 30, 17, 24, 32, 12, 37, 30, 14, 19],
       [36, 23, 37, 34, 33, 14, 23, 16, 33, 24],
       [39, 11, 30, 20, 19, 27, 14, 30, 29, 27],
       [17, 23, 36, 36, 10, 23, 31, 15, 37, 25],
       [10, 11, 27, 30, 10, 34, 31, 31, 21, 21],
       [12, 38, 36, 28, 15, 25, 17, 13, 13, 21],
       [37, 25, 27, 30, 29, 29, 19, 12, 22, 27],
       [33, 25, 21, 11, 31, 26, 22, 25, 29, 18]], dtype=int32)

In [80]:
arr2 = np.random.randint(1,10,(3,3)) 
arr2

array([[1, 9, 4],
       [5, 2, 9],
       [1, 3, 1]], dtype=int32)

In [81]:
arr2[::-1] #REVERSE,rows will go first

array([[1, 3, 1],
       [5, 2, 9],
       [1, 9, 4]], dtype=int32)

In [83]:
arr2[::-2] #rows are shifted here

array([[1, 3, 1],
       [1, 9, 4]], dtype=int32)

In [84]:
arr1

array([[16, 31, 33, 14, 26, 27, 15, 34, 19, 12],
       [23, 30, 14, 28, 29, 19, 36, 17, 12, 14],
       [33, 30, 17, 24, 32, 12, 37, 30, 14, 19],
       [36, 23, 37, 34, 33, 14, 23, 16, 33, 24],
       [39, 11, 30, 20, 19, 27, 14, 30, 29, 27],
       [17, 23, 36, 36, 10, 23, 31, 15, 37, 25],
       [10, 11, 27, 30, 10, 34, 31, 31, 21, 21],
       [12, 38, 36, 28, 15, 25, 17, 13, 13, 21],
       [37, 25, 27, 30, 29, 29, 19, 12, 22, 27],
       [33, 25, 21, 11, 31, 26, 22, 25, 29, 18]], dtype=int32)

In [86]:
arr1[0:5] # 0 to 4th row

array([[16, 31, 33, 14, 26, 27, 15, 34, 19, 12],
       [23, 30, 14, 28, 29, 19, 36, 17, 12, 14],
       [33, 30, 17, 24, 32, 12, 37, 30, 14, 19],
       [36, 23, 37, 34, 33, 14, 23, 16, 33, 24],
       [39, 11, 30, 20, 19, 27, 14, 30, 29, 27]], dtype=int32)

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4])


In [15]:
print(np.zeros(5))               #5 zeros will be there
print(np.zeros((2, 3)))          #2 row and 3 column
print(np.zeros((5), dtype=int))
print(np.zeros((4, 10))) #will be converted into int
#ALL THESE CREATES AN AARAY FILLED WITH ZEROES

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[0 0 0 0 0]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
print(np.random.rand(3) )       # float values
print(np.random.randint(1, 10, 5)) #int values


[0.09315141 0.76779172 0.59082096]
[2 5 9 8 5]


### Create a NumPy array with values from 1 to 10

In [19]:
import numpy as np
np.arange(11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Create a 1D array of five zeros

In [20]:
import numpy as np
np.zeros(5)                  #in float

array([0., 0., 0., 0., 0.])

In [22]:
import numpy as np
np.zeros((5),dtype = int)   #in int

array([0, 0, 0, 0, 0])

### Generate 4 random integers between 10 and 50

In [36]:
import numpy as np
np.random.randint(10,50,5)

array([46, 41, 22, 34, 23], dtype=int32)

### Access the last element of an array

In [40]:
import numpy as np
array = [1,2,3,4,4,5,5]
array[4:7]

[4, 5, 5]

### Create an array using np.arange() from 0 to 20 with step 3

In [43]:
import numpy as np
np.arange(0,21,3)

array([ 0,  3,  6,  9, 12, 15, 18])

### Slice an array to get every second element

In [44]:
import numpy as np
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

### Create a 3×3 zero matrix

In [47]:
import numpy as np
np.zeros((2,3))    #USE 2 BRACEKETS

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
a = np.array([2, 4, 6, 8])
b = a[1:3]
b[1] = 99
print(a)

[ 2  4 99  8]


## predict output

In [2]:
import numpy as np
a = np.array([2, 4, 6, 8])
b = a[1:3]
b[1] = 99
print(a)
#the indexing is done in b variable as b is equals to a

[ 2  4 99  8]


In [3]:
a = np.zeros(4)
print(a.dtype) #64 bits are used to store one number in a memory

float64


In [5]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[::2])
#start to end with 2 step

[1 3 5]


In [6]:
a = np.array([10, 20, 30, 40])
print(a[::-1])
# it will be in reverse

[40 30 20 10]


In [7]:
a = np.array([3, 6, 9, 12])
b = a[1:3]
b[:] = 0
print(a)

[ 3  0  0 12]


In [9]:
#to avod the prior situation
a = np.array([3, 6, 9, 12])
b = a[1:3].copy()
b[:] = 0
print(a)

[ 3  6  9 12]


In [10]:
a = np.array([2, 4, 6, 8, 10])
b = a[2:]
b[0] = 99
print(a)

[ 2  4 99  8 10]


In [12]:
a = np.array([1, 2, 3, 4])
b = a[1:3].copy()
b[0] = 100
print(a)  #copy was there ,therfore it will give the original array
print(b)  #if b is printed seprately then it will work

[1 2 3 4]
[100   3]
